jakarta.persistence.jdbc.url=jdbc:sqlite:db.db
hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true